// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFOjhniY44frVqqt0iwL4R925V2ZqROOE',
    appId: '1:780511425948:android:469c43f3bd3937548ac459',
    messagingSenderId: '780511425948',
    projectId: 'food-delivery-b361f',
    storageBucket: 'food-delivery-b361f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNYIxO8o-dUlWRDPgxqvrhQisOTV6Qx70',
    appId: '1:780511425948:ios:a98e1373d5b387088ac459',
    messagingSenderId: '780511425948',
    projectId: 'food-delivery-b361f',
    storageBucket: 'food-delivery-b361f.firebasestorage.app',
    androidClientId: '780511425948-93aj613p6nv6j00ngi3kh9e01slflimd.apps.googleusercontent.com',
    iosClientId: '780511425948-qhnj6ct1a3erqfrl9rqadijq66rrb09u.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryAdminApp',
  );
}
